services:
  postgresql:
    container_name: temp_postgres
    image: postgres:16-alpine
    ports:
      - 5433:5432
    environment:
      POSTGRES_PASSWORD: 0000
      POSTGRES_USER: valik
      POSTGRES_DB: ex
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_INITDB_ARGS: --auth-host=trust
